build:
  image: docker:28.2.2
  stage: build
  services:
    - docker:28.2.2-dind
  script:

    # Build
    - docker build -t conways-game-of-life-builder --load .
    - docker run --rm -v "$PWD:/home/user/workspace" conways-game-of-life-builder
    - docker rmi conways-game-of-life-builder

    # Create Artefact
    - mkdir site
    - mv index.html out/main.js site
    - cd site && tar -Jcf ../conways-game-of-life.tar.xz .

  artifacts:
    paths:
      - conways-game-of-life.tar.xz

