build:
  image: node:22-bookworm
  stage: build
  before_script:
    - apt-get update
    - apt-get install --yes --no-install-recommends xz-utils
  script:
    - npm ci
    - npm run publish
  artifacts:
    paths:
      - conways-game-of-life.tar.xz
